function eqSet = equationSet(in1)
%EQUATIONSET
%    EQSET = EQUATIONSET(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    20-Mar-2015 18:13:12

alphaR1 = in1(:,1);
alphaR2 = in1(:,2);
alphaR3 = in1(:,3);
alphaR4 = in1(:,4);
phiA = in1(:,5);
psiA = in1(:,6);
thetaC1 = in1(:,7);
thetaC2 = in1(:,8);
thetaC3 = in1(:,9);
thetaC4 = in1(:,10);
t2 = cos(psiA);
t3 = cos(thetaC1);
t4 = cos(phiA);
t5 = cos(thetaC2);
t6 = sin(phiA);
t7 = sin(psiA);
t8 = cos(thetaC3);
t9 = cos(thetaC4);
t10 = sin(thetaC1);
t11 = sin(thetaC2);
t12 = sin(thetaC3);
t13 = sin(thetaC4);
eqSet = reshape([alphaR1.*9.22129783761058e-1-t2.*t3.*(3.3e1./1.0e2)+5.340026917539057e-1,alphaR1.*(-3.672415553759845e-1)-t4.*t10.*(3.3e1./1.0e2)-t3.*t6.*t7.*(3.3e1./1.0e2)-3.181543123402161e-1,alphaR1.*1.216975838125477e-1-t6.*t10.*(3.3e1./1.0e2)+t3.*t4.*t7.*(3.3e1./1.0e2)+9.574195129065732e-1,alphaR2.*9.739075222625051e-1-t2.*t5.*(3.3e1./1.0e2)+5.07664254335759e-1,alphaR2.*(-2.249542354527029e-1)-t4.*t11.*(3.3e1./1.0e2)-t5.*t6.*t7.*(3.3e1./1.0e2)-2.178411426736917e-1,alphaR2.*(-2.999550020249575e-2)-t6.*t11.*(3.3e1./1.0e2)+t4.*t5.*t7.*(3.3e1./1.0e2)+9.918040849386967e-1,alphaR3.*8.410897575845478e-1-t2.*t8.*(3.3e1./1.0e2)+5.100556801173479e-1,alphaR3.*(-4.737892201613992e-1)-t4.*t12.*(3.3e1./1.0e2)-t6.*t7.*t8.*(3.3e1./1.0e2)-3.997951048509008e-1,alphaR3.*2.609440448548687e-1-t6.*t12.*(3.3e1./1.0e2)+t4.*t7.*t8.*(3.3e1./1.0e2)+5.313362250920181e-1,alphaR4.*8.775443430267478e-1-t2.*t9.*(3.3e1./1.0e2)+5.247708791264087e-1,alphaR4.*(-4.546306383002785e-1)-t4.*t13.*(3.3e1./1.0e2)-t6.*t7.*t9.*(3.3e1./1.0e2)-3.822395041903679e-1,alphaR4.*1.524037687868477e-1-t6.*t13.*(3.3e1./1.0e2)+t4.*t7.*t9.*(3.3e1./1.0e2)+4.92971005587267e-1],[3, 4]);
