function out1 = transA5_0(theta1,theta2,theta3)
%TRANSA5_0
%    OUT1 = TRANSA5_0(THETA1,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 5.9.
%    24-Mar-2015 11:39:32

t2 = cos(theta1);
t3 = sin(theta2);
t4 = cos(theta2);
t5 = sin(theta1);
t6 = cos(theta3);
t7 = t2.*t3;
t8 = t4.*t5.*6.123233995736766e-17;
t9 = t7+t8;
t10 = sin(theta3);
t11 = t2.*t4;
t13 = t3.*t5.*6.123233995736766e-17;
t12 = t11-t13;
t14 = t2.*t4.*6.123233995736766e-17;
t19 = t3.*t5;
t15 = t14-t19;
t16 = t2.*t3.*6.123233995736766e-17;
t17 = t4.*t5;
t18 = t16+t17;
out1 = reshape([t6.*t12-t9.*t10,t6.*t18+t10.*t15,-t3.*t6-t4.*t10,0.0,-t6.*t9-t10.*t12,t6.*t15-t10.*t18,-t4.*t6+t3.*t10,0.0,-t5,t2,6.123233995736766e-17,0.0,t5.*(4.9e1./5.0e2)+t2.*t4.*4.318e-1-t3.*t5.*2.644012439359136e-17+t6.*t12.*(2.7e1./1.0e2)-t9.*t10.*(2.7e1./1.0e2),t2.*(-4.9e1./5.0e2)+t2.*t3.*2.644012439359136e-17+t4.*t5.*4.318e-1+t6.*t18.*(2.7e1./1.0e2)+t10.*t15.*(2.7e1./1.0e2),t3.*(-4.318e-1)-t3.*t6.*(2.7e1./1.0e2)-t4.*t10.*(2.7e1./1.0e2)+6.66e-1,1.0],[4, 4]);
